notifications:
  email: false

sudo: true
language: haskell


git:
  depth: 5


cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/karun012/doctest-discover/.stack-work"


addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc'
    packages:
      - libgmp-dev
      - cabal-install-2.0


before_install:

  - mkdir -p ~/.local/bin
  - export PATH="$HOME/.local/bin:$PATH"
  - travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version


install:

  - travis_wait 30 stack setup --no-terminal
  - stack ghc -- --version

  - travis_wait 40 stack build --only-dependencies --no-terminal
  - travis_wait 40 stack build --test --bench --no-run-tests --no-run-benchmarks --no-terminal


script:

  - travis_wait 40 stack build --test --no-terminal


deploy:
  provider: hackage
  username: karun012
  password:
    secure: GrFiGoZYG9pcdm8dfle8eHAgDPiR21NkkLj28aKqWvjCoTaiML44dQK/5/llfWdAjxloBZp4NMxYeuCkeycyVsJWEfyTilxc5u3gwDcX6Q2Fi3Qc5SBwPmympUp/JCN17aJUHbOjzeCW20zrVyNIzJCHYXoS+Q7ZXBVARTK+pMI=
  on:
    repo: karun012/doctest-discover
