notifications:
  email: false

sudo: false
language: haskell

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- stack build --test --no-terminal --install-ghc

deploy:
  provider: hackage
  username: karun012
  password:
    secure: GrFiGoZYG9pcdm8dfle8eHAgDPiR21NkkLj28aKqWvjCoTaiML44dQK/5/llfWdAjxloBZp4NMxYeuCkeycyVsJWEfyTilxc5u3gwDcX6Q2Fi3Qc5SBwPmympUp/JCN17aJUHbOjzeCW20zrVyNIzJCHYXoS+Q7ZXBVARTK+pMI=
  on:
    repo: karun012/doctest-discover
