notifications:
  email: false

sudo: false

language: haskell

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc' # PPA of Haskell packages
    packages:
      - libgmp-dev           # required by cabal
      - cabal-install-2.0    # required by GHC 8.x

ghc:
  - 8.0

before_install
  - mkdir -p “$HOME/.local/bin”
  - export PATH="$HOME/.local/bin:$PATH"
  - travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C "$HOME/.local/bin" '*/stack'
  - stack --version

install
  - travis_wait 30 stack setup --no-terminal
  - stack ghc -- --version
  - travis_wait 40 stack build --no-terminal --only-dependencies
  - travis_wait 40 stack build --no-terminal --test 

script:
  - travis_wait 40 stack build --no-terminal --test


deploy:
  provider: hackage
  username: karun012
  password:
    secure: GrFiGoZYG9pcdm8dfle8eHAgDPiR21NkkLj28aKqWvjCoTaiML44dQK/5/llfWdAjxloBZp4NMxYeuCkeycyVsJWEfyTilxc5u3gwDcX6Q2Fi3Qc5SBwPmympUp/JCN17aJUHbOjzeCW20zrVyNIzJCHYXoS+Q7ZXBVARTK+pMI=
  on:
    repo: karun012/doctest-discover
