notifications:
  email: false

language: nix

cache:
  directories:
    - $HOME/.stack

install:
  - stack install --no-terminal --install-ghc --only-dependencies

script:
  - stack build 
  - stack test --no-terminal 

after_success:
  - stack upload
